[package]
name = "tetris-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"